stages:
  - trigger

.trigger_rules: &trigger_rules
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - .gitlab-ci.yml
        - .vscode/**
        - constant/**
        - decorator/**
        - docs/**
        - enum/**
        - guard/**
        - helper/**
        - interface/**
        - pipe/**
        - schema/**
        - strategy/**

trigger_gateway:
  stage: trigger
  trigger:
    project: chienbinhthephai/gateway
    branch: main
  <<: *trigger_rules

trigger_auth:
  stage: trigger
  trigger:
    project: chienbinhthephai/auth
    branch: main
  <<: *trigger_rules

trigger_user:
  stage: trigger
  trigger:
    project: chienbinhthephai/user
    branch: main
  <<: *trigger_rules

trigger_redis:
  stage: trigger
  trigger:
    project: chienbinhthephai/redis
    branch: main
  <<: *trigger_rules

trigger_wallet:
  stage: trigger
  trigger:
    project: chienbinhthephai/wallet
    branch: main
  <<: *trigger_rules
