version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:22.0

jobs:
  # ======================
  # 1️⃣ LINT
  # ======================
  lint:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run lint
          command: pnpm run lint

  # ======================
  # 2️⃣ TEST
  # ======================
  test:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run test
          command: npm run test

workflows:
  version: 2

  branch_workflow:
    jobs:
      - lint:
          filters:
            branches:
              ignore: main

      - test:
          requires:
            - lint
          filters:
            branches:
              ignore: main
