image: alpine:latest

stages:
  - lint
  - test
  - build
  - subtree
  - push-repo-triggers

variables:
  NODE_VERSION: '22'

default:
  image: node:22
  before_script:
    - node -v
    - npm ci

cache:
  paths:
    - node-modules/

lint:
  stage: lint
  script:
    - pnpm run lint
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: on_success

test:
  stage: test
  script:
    - npm run test
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: on_success
