export const RABBITMQ_QUEUE = {
  RMQ_CLIENT: 'RABBITMQ_QUEUE',
  USER_CLIENT: 'USER_QUEUE',
  MAILER_CLIENT: 'MAILER_CLIENT',
  AUTH_CLIENT: 'AUTH_QUEUE',
  REDIS_CLIENT: 'REDIS_QUEUE',
  WALLET_CLIENT: 'WALLET_QUEUE',
  TRANSACTION_CLIENT: 'TRANSACTION_QUEUE',
};
